config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :bigint           not null, primary key
#  caption    :text
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :photo do |attachable|
    attachable.variant :thumb,resize_to_limit:[200,300]
  end
  
  has_many :comments, as: :commentable,dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  is_karina              :boolean          default(FALSE), not null
#  name                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :profile_photo

  has_many :photos, dependent: :destroy
  has_many :comments, as: :commentable,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile_photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:profile_photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def new
      @comment = Comment.new
    end

    def create
      @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.build(comment_params)
    @comment.user = current_user # Asocia el comentario al usuario actualmente autenticado

      if @comment.save
        redirect_to request.fullpath, notice: 'Comentario creado correctamente.'
      else
        redirect_to request.fullpath, alert: 'No se pudo crear el comentario.'
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  
    def commentable_path
      # Lógica para redirigir a la página de detalle de Photo o User, dependiendo del tipo de comentario
    end
  
    def find_commentable
      if params[:commentable_type] == 'Photo'
        Photo.find(params[:commentable_id])
      elsif params[:commentable_type] == 'User'
        User.find(params[:commentable_id])
      end
    end
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # before_action :authenticate_user!, only:[:new,:create]
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  def new
    if current_user.is_karina?
      @photo = current_user.photos.build
    else
      redirect_to root_path, alert: 'Solo Karina puede subir fotos.'
    end
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = current_user.photos.build(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:caption,:photo, :user_id)
    end
                                   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KariPic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    
    <% if user_signed_in? %>
      <%= render 'shared/navbar' %>
    <% end %>
    
    <main class="container text-center abs-center">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </main>
    <%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/166fe20303.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KariPic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <main class="container text-center">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/166fe20303.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/photos/_comment.html.erb
 <!-- Mostrar comentarios existentes -->
    <strong class="text-body-secondary">Comentarios</strong>
    <% sorted_comments = photo.comments.sort_by { |comment| comment.created_at }.reverse %>
    <% sorted_comments.each do |comment| %>
    <div class="container ">
        <p class="m-0">
            <%= image_tag comment.user.profile_photo,alt:"profile_photo",class:"profile_photo" %>
            <strong><%= comment.user.try(:name) %>:</strong>
        </p>
        <p class="m-0">
            <%= comment.content %>  
        </p >
        <small class="text-body-secondary text-end mb-2">
         <%= time_ago_in_words(comment.created_at) %> ago.
        </small>
    </div>
    <% end %>

app/views/photos/_comment_form.html.erb
<!-- app/views/photos/_comment_form.html.erb -->
<%= form_with(model: @photo.comments.build, url: photo_comments_path(@photo)) do |form| %>
  <%= form.hidden_field :commentable_id, value: @photo.id %>
  <%= form.hidden_field :commentable_type, value: @photo.class.to_s %>

  <div class="field">
    <%= form.text_area :content, placeholder: 'Escribe un comentario...' %>
  </div>
  <%= form.submit 'Agregar comentario', class: 'btn btn-primary' %>
<% end %>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :photo %><br>
    <%= form.file_field :photo  %>
  </div>

  <div>
    <%= form.label :caption, style: "display: block" %>
    <%= form.text_area :caption %>
  </div>



  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>" class="card mb-3 text-center" >
  <%= image_tag photo.photo,class:"card-img-top" %>
  <div class="card-body">
    <p class="card-text">
      <span>
        <%= photo.caption  %>
      </span>
      <br>
      <small class="text-body-secondary">
        Creada <%= time_ago_in_words(photo.created_at) %> atrás.
      </small>
    </p>
    
    
   </div>
   <div class="card-footer text-start">
      <% if current_page?(photo_path(photo.id)) %>
        <!-- Mostrar comentarios existentes -->
        <%= render 'comment' ,photo:photo%>
        <!-- Formulario para agregar nuevos comentarios -->
        <%= render 'comment_form', commentable: @photo %>
      <% else %>
        <% last_comment = photo.comments.last %>
        <% if last_comment %>
          <div class="comment">
            <p><strong><%= last_comment.user.name %>:</strong> <%= last_comment.content %></p>
          </div>
        <% end %>
      <% end %>
    <% if controller_name == 'photos' && action_name != 'show' %>
      <p class="text-end">
        <%= link_to "Show this photo", photo ,class:"btn btn-primary"%>
      </p>
    <% end %>
      
   </div>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<h1>Photos</h1>
<% if current_user.is_karina? %>
<%= link_to "New photo", new_photo_path %> <br>
<%end%>
  <div id="photos" class="row row-cols-1 row-cols-md-2 g-0">

    <% @photos.each do |photo| %>
      <div class="col">
        <%= render photo,photo:photo %>
      </div>
    <% end %>
  
  </div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<div class="text-center row row-cols-1 row-cols-md-2 g-0">

  <%= render @photo %>
</div>
<br>
<div>
  <%= link_to "Back to photos", photos_path %>|
<% if current_user.is_karina? %>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> 

  <%= button_to "Destroy this photo", @photo, method: :delete ,class:"btn btn-danger"%>
</div>
<% else %>
  
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 
    <small>Toffy Caluga</small>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark align-items-center justify-content-center" data-bs-theme="dark">
  <div class="container-fluid ">
    
      <p class="navbar-brand">
      <% if current_user.profile_photo.present? %>
        <%= image_tag current_user.profile_photo,alt:"profile_photo",class:"profile_photo navbar-brand" %>
      <% else %>
        <i class="fa-solid fa-circle-user navbar-brand"></i>
      <% end %> 

      <%=current_user.name%>
      </p>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-label="toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div id="navbar" class="collapse navbar-collapse  mb-3 mt-1">
        <ul class="navbar-nav me-auto p-0">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link" %>
          </li>
        </ul>
      <div class="d-flex">
          <%= button_to 'Cerrar sesion', destroy_user_session_path,method: :delete , class:"btn btn-outline-danger" %>
      </div>
      </div>
  </div>
</nav>